### ISSUE TITLE
Project ID being injected from SA

### ISSUE THREAD

**Issue by sekhrivijay** [GoogleCloudPlatform/cloud-debug-java#15] opened 2019-04-26 16:08 UTC
The projectID where the debugger registers is being picked up from service account json file. 

` @Key("project_id")
    private String projectId = null;`

This creates a problem when you have service account from different  project but want to use debugger in another project.  Providing environment variable PROJECT_ID should override the projectId from service account .

**Comment by hrasadi** [comment] 2019-04-29 13:35
I don't think it's a problem. You can use a second SA for debugger and introduce it when starting the debugger. At any rate, by design, service account has to have one project ID assigned to it so you cannot use a service account with a project that is not owning it. Refer to this piece of docs for more information and let me know if you have further questions:

https://github.com/GoogleCloudPlatform/cloud-debug-java/blob/387a904d58260637c2433c2191395fd3d93cd765/src/agent/internals/src/main/java/com/google/devtools/cdbg/debuglets/java/ServiceAccountAuth.java#L130

**Closed by hrasadi** 2019-04-29 13:35 UTC
